- hosts: all
  become: true

  tasks:
    - name: optimize dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        mode: 0644
      loop:
        - {regexp: '^fastestmirror', line: 'fastestmirror=True'}
        - {regexp: '^max_parallel_downloads', line: 'max_parallel_downloads=10'}

    - name: install RPM Fusion repos
      ansible.builtin.dnf:
        name:
         - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
         - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: add Flathub repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: install base packages
      ansible.builtin.dnf:
        name:
          - bat
          - cu
          - fortune-mod
          - fzf
          - htop
          - keychain
          - ncdu
          - neofetch
          - nmap
          - pwgen
          - restic
          - ripgrep
          - solaar
          - sshfs
          - transmission
          - zsh
          - zsh-autosuggestions
        state: present
