- hosts: all
  become: true
  vars:
    gocryptfs_version: 2.4.0
    gocryptfs_tar_checksum: sha256:57f540277816e9bceb9220f9f3604da374df9a6e804696dc72c988dcda710c59
    gocryptfs_bin_checksum: 5ca700f6e7dde40f8c9c7f85ee7e2c5dd77025443b0dd21f4e172bfb1b6ec5bc

  tasks:
    - name: optimize dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        mode: 0644
      loop:
        - {regexp: '^fastestmirror', line: 'fastestmirror=True'}
        - {regexp: '^max_parallel_downloads', line: 'max_parallel_downloads=10'}

    - name: install RPM Fusion repos
      ansible.builtin.dnf:
        name:
         - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
         - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: add Flathub repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: install base packages
      ansible.builtin.dnf:
        name:
          - autofs
          - bat
          - cu
          - dnf5
          - dua-cli
          - fd-find
          - fortune-mod
          - fzf
          - htop
          - hyperfine
          - keychain
          - lm_sensors
          - ncdu
          - neofetch
          - nmap
          - pwgen
          - remove-retired-packages
          - restic
          - ripgrep
          - rpmconf
          - solaar
          - sshfs
          - symlinks
          - telnet
          - transmission
          - wl-clipboard
          - zsh
          - zsh-autosuggestions
          - zstd
        state: present

    - name: check if gocryptfs is installed
      ansible.builtin.stat:
        path: /usr/local/bin/gocryptfs
        checksum_algorithm: sha256
      register: localbingocryptfs

    - name: "download gocryptfs {{ gocryptfs_version }}"
      ansible.builtin.get_url:
        url: "https://github.com/rfjakob/gocryptfs/releases/download/v{{ gocryptfs_version }}/gocryptfs_v{{ gocryptfs_version }}_linux-static_amd64.tar.gz"
        dest: "/tmp/gocryptfs_v{{ gocryptfs_version }}_linux-static_amd64.tar.gz"
        mode: 0644
        checksum: "{{ gocryptfs_tar_checksum }}"
      when: localbingocryptfs.stat.checksum is not defined or localbingocryptfs.stat.checksum != gocryptfs_bin_checksum

    - name: "unpack gocryptfs {{ gocryptfs_version }}"
      ansible.builtin.unarchive:
        src: "/tmp/gocryptfs_v{{ gocryptfs_version }}_linux-static_amd64.tar.gz"
        dest: /usr/local/bin
        include: gocryptfs
        owner: root
        group: root
      when: localbingocryptfs.stat.checksum is not defined or localbingocryptfs.stat.checksum != gocryptfs_bin_checksum

    - name: "delete downloaded gocryptfs {{ gocryptfs_version }} tarball"
      ansible.builtin.file:
        name: "/tmp/gocryptfs_v{{ gocryptfs_version }}_linux-static_amd64.tar.gz"
        state: absent
      when: localbingocryptfs.stat.checksum is not defined or localbingocryptfs.stat.checksum != gocryptfs_bin_checksum

    - name: install warehouse
      community.general.flatpak:
        remote: flathub
        name: io.github.flattool.Warehouse
        state: present
