- hosts: all
  become: true

  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
          - bat
          - fortune-mod
          - fzf
          - htop
          - keychain
          - neovim
          - ripgrep
          - sqlite
          - vim-enhanced
          - zsh
          - zsh-autosuggestions
        state: present
