- hosts: all
  become: true
  vars:
    compass_version: 1.32.2

  tasks:
  - name: add MongoDB 5.0 repo
    ansible.builtin.yum_repository:
      name: mongodb-org-5.0
      description: MongoDB Repository
      file: mongodb-org-5.0
      baseurl: https://repo.mongodb.org/yum/redhat/8/mongodb-org/5.0/$basearch/
      gpgkey: https://www.mongodb.org/static/pgp/server-5.0.asc
      gpgcheck: yes

  - name: install MongoDB shell and tools
    ansible.builtin.dnf:
      name:
        - mongodb-database-tools
        - mongodb-mongosh
      state: present

  - name: install MongoDB Compass
    ansible.builtin.dnf:
      name: "https://downloads.mongodb.com/compass/mongodb-compass-{{ compass_version }}.x86_64.rpm"
      state: present
      disable_gpg_check: true

  - name: install pgcli
    ansible.builtin.dnf:
      name: pgcli
      state: present

  - name: install mycli
    ansible.builtin.dnf:
      name: mycli
      state: present

  - name: install RESP.app
    community.general.flatpak:
      name: app.resp.RESP
      state: present

  - name: install iredis
    ansible.builtin.pip:
      name: iredis
