- hosts: all
  become: true
  vars:
    mkcert_version: 1.4.4
    mkcert_cheksum: sha256:6d31c65b03972c6dc4a14ab429f2928300518b26503f58723e532d1b0a3bbb52
    fx_version: 24.1.0
    fx_checksum: sha256:910f788c5f4b329aff9744b5f89e111303ebdc70e233e7f3b860c38941e61a5e

  tasks:
    - name: install virtualization group
      ansible.builtin.dnf:
        name:
          - "@virtualization"
          - virt-top
        state: present

    - name: enable libvirtd service
      ansible.builtin.systemd:
        name: libvirtd
        enabled: yes

    - name: enable Visual Studio Code repo
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes

    - name: enable GoReleaser repo for nfpm
      ansible.builtin.yum_repository:
        name: goreleaser
        description: GoReleaser
        file: goreleaser
        baseurl: https://repo.goreleaser.com/yum/
        gpgcheck: no

    - name: add Charm repo for glow
      ansible.builtin.yum_repository:
        name: charm
        description: Charm
        file: charm
        baseurl: https://repo.charm.sh/yum
        gpgkey: https://repo.charm.sh/yum/gpg.key
        gpgcheck: yes

    - name: install develop packages
      ansible.builtin.dnf:
        name:
          - code
          - composer
          - direnv
          - filezilla
          - gh
          - glow
          - go-task
          - graphviz
          - neovim
          - nodejs
          - nfpm
          - nss-tools
          - patch
          - php-cli
          - python3-ansible-lint
          - python3-pip
          - sqlite
          - upx
          - vim-enhanced
          - zeal
        state: present

    - name: symlink go-task to task
      ansible.builtin.file:
        src: /usr/bin/go-task
        dest: /usr/bin/task
        owner: root
        group: root
        state: link

    - name: install Insomnia
      community.general.flatpak:
        remote: flathub
        name: rest.insomnia.Insomnia
        state: present

    - name: install Postman
      community.general.flatpak:
        remote: flathub
        name: com.getpostman.Postman
        state: present

    - name: remove ngrok
      ansible.builtin.file:
        path: /usr/local/bin/ngrok
        state: absent

    - name: "install mkcert {{ mkcert_version }}"
      ansible.builtin.get_url:
        url: "https://github.com/FiloSottile/mkcert/releases/download/v{{ mkcert_version }}/mkcert-v{{ mkcert_version }}-linux-amd64"
        dest: /usr/local/bin/mkcert
        mode: 0755
        owner: root
        group: root
        checksum: "{{ mkcert_cheksum }}"

    - name: "install fx {{ fx_version }}"
      ansible.builtin.get_url:
        url: "https://github.com/antonmedv/fx/releases/download/{{ fx_version }}/fx_linux_amd64"
        dest: /usr/local/bin/fx
        mode: 0755
        owner: root
        group: root
        checksum: "{{ fx_checksum }}"

    - name: remove task package
      ansible.builtin.dnf:
        name: task
        state: absent

    - name: remove dasel
      ansible.builtin.file:
        path: /usr/local/bin/dasel
        state: absent
