- hosts: all
  become: true

  tasks:
    - name: install virtualization group
      ansible.builtin.dnf:
        name:
          - "@virtualization"
          - virt-top
        state: present

    - name: enable libvirtd service
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: enable Visual Studio Code repo
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes

    - name: enable GoReleaser repo for nfpm
      ansible.builtin.yum_repository:
        name: goreleaser
        description: GoReleaser
        file: goreleaser
        baseurl: https://repo.goreleaser.com/yum/
        gpgcheck: no

    - name: install develop packages
      ansible.builtin.dnf:
        name:
          - code
          - composer
          - direnv
          - filezilla
          - graphviz
          - neovim
          - nodejs
          - nfpm
          - php-cli
          - python3-ansible-lint
          - python3-pip
          - sqlite
          - upx
          - vim-enhanced
          - zeal
        state: present

    - name: install Insomnia
      community.general.flatpak:
        remote: flathub
        name: rest.insomnia.Insomnia
        state: present

    - name: install Postman
      community.general.flatpak:
        remote: flathub
        name: com.getpostman.Postman
        state: present

    - name: install GitHub CLI
      ansible.builtin.dnf:
        name: https://github.com/cli/cli/releases/download/v2.14.6/gh_2.14.6_linux_amd64.rpm
        state: present
        disable_gpg_check: true

    - name: remove ngrok
      ansible.builtin.file:
        path: /usr/local/bin/ngrok
        state: absent

    - name: install mkcert
      ansible.builtin.get_url:
        url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
        dest: /usr/local/bin/mkcert
        mode: 0755
        owner: root
        group: root
        checksum: sha256:6d31c65b03972c6dc4a14ab429f2928300518b26503f58723e532d1b0a3bbb52

    - name: install go-task
      ansible.builtin.dnf:
        name: https://github.com/go-task/task/releases/download/v3.14.1/task_linux_amd64.rpm
        state: present
        disable_gpg_check: true

    - name: install dasel
      ansible.builtin.get_url:
        url: https://github.com/TomWright/dasel/releases/download/v1.26.0/dasel_linux_amd64
        dest: /usr/local/bin/dasel
        owner: root
        group: root
        mode: 0755
        checksum: sha256:b52604b4c925250998f8e9a8feb8c21ad8c3a7ab984aa7967e61b000c352b6cb
