- hosts: all
  become: true

  tasks:
    - name: enable Visual Studio Code repo
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes

    - name: install develop packages
      ansible.builtin.dnf:
        name:
          - code
          - direnv
          - filezilla
          - neovim
          - python3-ansible-lint
          - sqlite
          - upx
          - vim-enhanced
          - zeal

    - name: install Insomnia
      community.general.flatpak:
        remote: flathub
        name: rest.insomnia.Insomnia
        state: present

    - name: install Postman
      community.general.flatpak:
        remote: flathub
        name: com.getpostman.Postman
        state: present

    - name: install GitHub CLI
      ansible.builtin.dnf:
        name: https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.rpm
        state: present
        disable_gpg_check: true

# add ngrok, nfpm, virtualbox (?)
