- hosts: all
  become: true
  vars:
    username: "{{ lookup('env', 'USERNAME') }}"
    ctop_version: 0.7.7
    ctop_checksum: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
    switch_version: 1.0.4
    switch_checksum: sha256:08229ed196de5ce08228d194e2e2379cb6cb7959fe8dfe70859352d2fd9d21a5
    dive_version: 0.10.0
    dive_checksum: sha256:9541997876d4985de66d0fa5924dac72258a3094ef7d3f6ef5fa5dcf6f6a47ad
    dive_bin_checksum: 9988233a21164920882eda6769fcf98969fb2b01fd4442ca022db88e4c4acbf2

  tasks:
    - name: enable Docker CE stable repo
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE stable repo
        file: docker-ce
        baseurl: 'https://download.docker.com/linux/fedora/$releasever/$basearch/stable'
        gpgkey: 'https://download.docker.com/linux/fedora/gpg'
        gpgcheck: yes

    - name: install Docker CE
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: enable Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: "add {{ username }} to docker group"
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: true

    - name: install ctop
      ansible.builtin.get_url:
        url: "https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-amd64"
        dest: /usr/local/bin/ctop
        checksum: "{{ ctop_checksum }}"
        mode: 0755

    - name: install compose-switch
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose-switch/releases/download/v{{ switch_version }}/docker-compose-linux-amd64"
        dest: /usr/local/bin/docker-compose
        checksum: "{{ switch_checksum }}"
        mode: 0755

    - name: check if dive is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/dive
        checksum_algorithm: sha256
      register: localbindive

    - name: "download dive {{ dive_version }}"
      ansible.builtin.get_url:
        url: "https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_amd64.tar.gz"
        dest: "/tmp/dive_{{ dive_version }}_linux_amd64.tar.gz"
        mode: 0644
        checksum: "{{ dive_checksum }}"
      when: localbindive.stat.checksum is not defined or localbindive.stat.checksum != dive_bin_checksum

    - name: "unpack dive {{ dive_version }}"
      ansible.builtin.unarchive:
        src: "/tmp/dive_{{ dive_version }}_linux_amd64.tar.gz"
        dest: /usr/local/bin
        include: dive
        owner: root
        group: root
      when: localbindive.stat.checksum is not defined or localbindive.stat.checksum != dive_bin_checksum

    - name: "delete downloaded dive {{ dive_version }} tarball"
      ansible.builtin.file:
        name: "/tmp/dive_{{ dive_version }}_linux_amd64.tar.gz"
        state: absent
      when: localbindive.stat.checksum is not defined or localbindive.stat.checksum != dive_bin_checksum
