- hosts: all
  become: true

  tasks:
    - name: install Steam
      community.general.flatpak:
        remote: flathub
        name: com.valvesoftware.Steam
        state: present

    - name: install steam-devices
      ansible.builtin.dnf:
        name: steam-devices
        state: present

    - name: install Space Cadet Pinball
      community.general.flatpak:
        remote: flathub
        name: com.github.k4zmu2a.spacecadetpinball
        state: present

    - name: install Lutris
      community.general.flatpak:
        remote: flathub
        name: net.lutris.Lutris
        state: present

    - name: install ProtonUp-Qt
      community.general.flatpak:
        remote: flathub
        name: net.davidotek.pupgui2
        state: present

    - name: install Boxtron & Roberta requirements
      ansible.builtin.dnf:
        name:
          - dosbox-staging
          - fluid-soundfont-gm
          - inotify-tools
          - scummvm
          - timidity++
        state: present
