- hosts: all
  vars:
    filesdir: ../files/gnome
    username: "{{ lookup('env', 'USERNAME') }}"
    homedir: "/home/{{ username }}"
    wallpapersdir: "{{ homedir }}/Pictures/Wallpapers"
    wallpaper: sebastian-svenson-d2w-_1LJioQ-unsplash.jpg

  tasks:
    - name: remove background logo extension
      become: true
      dnf:
        name: gnome-shell-extension-background-logo
        state: absent

    - name: install gui stuff
      become: true
      dnf:
        name:
          - dconf-editor
          - gnome-extensions-app
          - gnome-tweaks
          - jetbrains-mono-fonts
          - python3-psutil
          - sushi
        state: present

    - name: set xkb-options
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps', 'grp_led:caps', 'terminate:ctrl_alt_bksp']"
        state: present

    - name: use dark theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        state: present

    - name: show weekday in topbar
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        state: present

    - name: use rgba font antialiasing
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-antialiasing"
        value: "'rgba'"
        state: present

    - name: show battery percentage
      community.general.dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"
        state: present

    - name: no event sounds
      community.general.dconf:
        key: "/org/gnome/desktop/sound/event-sounds"
        value: "false"
        state: present

    - name: disable automatic suspend
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
        value: "'nothing'"
        state: present

    - name: power button interactive mode
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'interactive'"
        state: present

    - name: set idle delay (screen blank) to 15mins
      community.general.dconf:
        key: "/org/gnome/desktop/session/idle-delay"
        value: "uint32 900"
        state: present

    - name: use JetBrains Mono for monospace
      community.general.dconf:
        key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'JetBrains Mono 11'"
        state: present

    - name: terminal shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Terminal'"
    - name: terminal shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'gnome-terminal'"
    - name: terminal shortcut binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Super>Return'"

    - name: firefox shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'Firefox'"
    - name: firefox shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'firefox'"
    - name: firefox shortcut binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Shift><Super>f'"
    - name: enable custom keybindings
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

    - name: terminal no bell
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
        value: "false"
    - name: terminal scrollback lines
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollback-lines"
        value: "1000000"
    - name: terminal zoom in with ctrl+= in terminal
      dconf:
        key: "/org/gnome/terminal/legacy/keybindings/zoom-in"
        value: "'<Control>equal'"
    - name: do not use theme colors
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
        value: "false"
    - name: terminal background color (solarized dark)
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
        value: "'rgb(0,43,54)'"
    - name: terminal foreground color (solarized dark)
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
        value: "'rgb(131,148,150)'"
    - name: terminal palette (solarized dark)
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette"
        value: "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
    - name: increase terminal size columns
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns"
        value: 130
    - name: increase terminal size rows
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows"
        value: 36

    - name: TextEditor hightlight current line
      dconf:
        key: "/org/gnome/TextEditor/highlight-current-line"
        value: "true"
    - name: TextEditor show line numbers
      dconf:
        key: "/org/gnome/TextEditor/show-line-numbers"
        value: "true"
    - name: TextEditor show map
      dconf:
        key: "/org/gnome/TextEditor/show-map"
        value: "true"
    - name: TextEditor style solarized
      dconf:
        key: "/org/gnome/TextEditor/style-scheme"
        value: "'solarized-dark'"

    - name: "create {{ wallpapersdir }}"
      ansible.builtin.file:
        path: "{{ wallpapersdir }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: add Wallpaper
      ansible.builtin.copy:
        src: "{{ filesdir }}/{{ wallpaper }}"
        dest: "{{ wallpapersdir }}/{{ wallpaper }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644
    - name: set Wallpaper
      dconf:
        key: "/org/gnome/desktop/background/{{ item }}"
        value: "'file://{{ wallpapersdir }}/{{ wallpaper }}'"
      loop:
        - picture-uri
        - picture-uri-dark

    - name: show delete permanently in context menu
      dconf:
        key: "/org/gnome/nautilus/preferences/show-delete-permanently"
        value: "true"

    - name: sort directories first in file chooser
      dconf:
        key: "/org/gtk/settings/file-chooser/sort-directories-first"
        value: "true"

    - name: add Flatseal
      community.general.flatpak:
        name: com.github.tchx84.Flatseal
        state: present
