- hosts: all
  become: true
  vars:
    go_version: 1.19.3
    go_sha256: sha256:74b9640724fd4e6bb0ed2a1bc44ae813a03f1e72a4c76253e2d5c015494430ba

  tasks:
    - name: check if go is already installed
      ansible.builtin.stat:
        path: /usr/local/go
      register: usrlocalgo

    - name: "download go {{ go_version }}"
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        mode: 0644
        checksum: "{{ go_sha256 }}"
      when: usrlocalgo is defined and not usrlocalgo.stat.exists

    - name: "unpack go {{ go_version }}"
      ansible.builtin.unarchive:
        src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /usr/local
      when: usrlocalgo is defined and not usrlocalgo.stat.exists

    - name: "delete downloaded go {{ go_version }} tarball"
      ansible.builtin.file:
        name: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        state: absent
      when: usrlocalgo is defined and not usrlocalgo.stat.exists

    - name: add /usr/local/go in global path
      ansible.builtin.lineinfile:
        path: /etc/profile.d/golang.sh
        line: 'export PATH=$PATH:/usr/local/go/bin'
        create: yes
        mode: 0644
