- hosts: all
  become: true

  tasks:
    - name: ensure fedora-cisco-openh264 repo is enabled
      community.general.ini_file:
        path: /etc/yum.repos.d/fedora-cisco-openh264.repo
        section: fedora-cisco-openh264
        option: enabled
        value: 1
        no_extra_spaces: yes
        mode: 0644

    - name: install media plugins
      ansible.builtin.dnf:
        name:
          - ffmpeg
          - gstreamer1-plugins-base
          - gstreamer1-plugins-bad-*
          - gstreamer1-plugins-good-*
          - gstreamer1-plugins-ugly-*
          - gstreamer1-plugin-openh264
          - gstreamer1-libav
          - gstreamer-ffmpeg
          - lame*
          - mozilla-openh264
          - rocm-opencl
        exclude:
          - gstreamer1-plugins-bad-free-devel
          - lame-devel
        state: present

    - name: install media apps
      ansible.builtin.dnf:
        name:
          - audacity
          - darktable
          - espeak
          - gimp
          - HandBrake-gui
          - helvum
          - kdenlive
          - mpv
          - pavucontrol
          - vlc
        state: present

    - name: install OBS Studio
      community.general.flatpak:
        name: com.obsproject.Studio
        state: present

    - name: install spotify
      community.general.flatpak:
        name: com.spotify.Client
        state: present

    - name: install plex desktop
      community.general.flatpak:
        name: tv.plex.PlexDesktop
        state: present

    - name: install shotcut
      community.general.flatpak:
        name: org.shotcut.Shotcut
        state: present

    - name: remove NoiseTorch
      ansible.builtin.dnf:
        name: noisetorch
        state: absent

    - name: remove principis/NoiseTorch copr repo
      community.general.copr:
        name: principis/NoiseTorch
        state: absent

    - name: install curtail
      community.general.flatpak:
        name: com.github.huluti.Curtail
        state: present

    - name: install Mousai
      community.general.flatpak:
        name: io.github.seadve.Mousai
        state: present

    - name: add Charm repo for VHS
      ansible.builtin.yum_repository:
        name: charm
        description: Charm
        file: charm
        baseurl: https://repo.charm.sh/yum
        gpgkey: https://repo.charm.sh/yum/gpg.key
        gpgcheck: yes

    - name: install VHS
      ansible.builtin.dnf:
        name: vhs
        state: present
