- hosts: all
  become: true

  tasks:
    - name: ensure fedora-cisco-openh264 repo is enabled
      community.general.ini_file:
        path: /etc/yum.repos.d/fedora-cisco-openh264.repo
        section: fedora-cisco-openh264
        option: enabled
        value: 1
        no_extra_spaces: yes
        mode: 0644

    - name: install media plugins
      ansible.builtin.dnf:
        name:
          - ffmpeg
          - gstreamer1-plugins-base
          - gstreamer1-plugins-bad-*
          - gstreamer1-plugins-good-*
          - gstreamer1-plugins-ugly-*
          - gstreamer1-plugin-openh264
          - gstreamer1-libav
          - gstreamer-ffmpeg
          - lame*
          - mozilla-openh264
        exclude:
          - gstreamer1-plugins-bad-free-devel
          - lame-devel

    - name: upgrade with media libs
      ansible.builtin.shell:
        cmd: dnf group upgrade --with-optional Multimedia -y

    - name: install media apps
      ansible.builtin.dnf:
        name:
          - audacity
          - gimp
          - HandBrake-gui
          - kdenlive
          - mpv
          - obs-studio
          - pavucontrol
          - vlc

    - name: install spotify
      community.general.flatpak:
        name: com.spotify.Client
        state: present
