- hosts: all
  become: true
  vars:
    ddosify_version: 0.15.0
    ddosify_checksum: sha256:9abbdf2c0a7ecb3a344c7fd586c9ca273c9f2d32785537c322b6dd603aefaba3
    ddosify_bin_checksum: 991378646df739123bd1415ff8e581380c61991c08084bb6670212916d2dac68

  tasks:
    - name: enable Tailscale repo
      ansible.builtin.yum_repository:
        name: tailscale-stable
        description: Tailscale stable
        file: tailscale
        baseurl: 'https://pkgs.tailscale.com/stable/fedora/$basearch'
        gpgkey: 'https://pkgs.tailscale.com/stable/fedora/repo.gpg'
        gpgcheck: no
        repo_gpgcheck: yes

    - name: install network apps and tools
      ansible.builtin.dnf:
        name:
          - google-chrome-stable
          - python3-speedtest-cli
          - rclone
          - tailscale
          - testssl
        state: present

    - name: enable Tailscale daemon
      ansible.builtin.systemd:
        name: tailscaled
        state: started
        enabled: yes

    - name: check if ddosify is installed
      ansible.builtin.stat:
        path: /usr/local/bin/ddosify
        checksum_algorithm: sha256
      register: localbinddosify

    - name: "download ddosify {{ ddosify_version }}"
      ansible.builtin.get_url:
        url: "https://github.com/ddosify/ddosify/releases/download/v{{ ddosify_version }}/ddosify_{{ ddosify_version }}_linux_amd64.tar.gz"
        dest: "/tmp/ddosify_linux_amd64.tar.gz"
        mode: 0644
        checksum: "{{ ddosify_checksum }}"
      when: localbinddosify.stat.checksum is not defined or localbinddosify.stat.checksum != ddosify_bin_checksum

    - name: "unpack ddosify {{ ddosify_version }}"
      ansible.builtin.unarchive:
        src: "/tmp/ddosify_linux_amd64.tar.gz"
        dest: /usr/local/bin
        include: ddosify
        owner: root
        group: root
      when: localbinddosify.stat.checksum is not defined or localbinddosify.stat.checksum != ddosify_bin_checksum

    - name: "delete downloaded ddosify {{ ddosify_version }} tarball"
      ansible.builtin.file:
        name: "/tmp/ddosify_linux_amd64.tar.gz"
        state: absent
      when: localbinddosify.stat.checksum is not defined or localbinddosify.stat.checksum != ddosify_bin_checksum
