- hosts: all
  become: true

  tasks:
    - name: install 32-bit glibc for compatibility
      ansible.builtin.dnf:
        name: glibc.i686
        state: present

    - name: install Brother HL-1223WE drivers
      ansible.builtin.dnf:
        name:
          - https://download.brother.com/welcome/dlf102475/hl1210wlpr-3.0.1-1.i386.rpm
          - https://download.brother.com/welcome/dlf102476/hl1210wcupswrapper-3.0.1-1.i386.rpm
        state: present
        disable_gpg_check: true

    - name: uninstall pangox-compat from Fedora 32
      ansible.builtin.dnf:
        name: pangox-compat
        releasever: "32"
        state: absent

    - name: uninstall Canon Pixma MX925 drivers
      ansible.builtin.dnf:
        name:
          - cnijfilter-common
          - cnijfilter-mx920series
        state: absent
