- hosts: all
  become: true

  tasks:
    - name: install Bitwarden
      community.general.flatpak:
        remote: flathub
        name: com.bitwarden.desktop
        state: present

    - name: install nextcloud-client
      ansible.builtin.dnf:
        name: nextcloud-client
        state: present

    - name: install Calibre
      ansible.builtin.dnf:
        name: calibre
        state: present

    - name: install Discord
      community.general.flatpak:
        remote: flathub
        name: com.discordapp.Discord
        state: present

    - name: install Slack
      community.general.flatpak:
        remote: flathub
        name: com.slack.Slack
        state: present

    - name: install Zoom
      community.general.flatpak:
        remote: flathub
        name: us.zoom.Zoom
        state: present
