- hosts: all
  become: true

  tasks:
    - name: install bitwarden
      community.general.flatpak:
        remote: flathub
        name: com.bitwarden.desktop
        state: present

    - name: install chrome
      ansible.builtin.dnf:
        name: google-chrome-stable
        state: present
